# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
target 'ReadsSwift' do
    pod 'BlueShift-iOS-SDK'
    pod 'Kingfisher'
    pod 'Firebase/Analytics'
    pod 'Firebase/Performance'
    pod 'Firebase/Crashlytics'
    pod 'Fabric'
end

target 'NotificationService' do
    pod 'BlueShift-iOS-Extension-SDK'
end

target 'NotificationContent' do
    pod 'BlueShift-iOS-Extension-SDK'
end

