# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks! 
target 'ReadsSwift' do
    pod 'BlueShift-iOS-SDK', '~> 2.4.0'
end

target 'NotificationService' do
    pod 'BlueShift-iOS-Extension-SDK'
end

target 'NotificationContent' do
    pod 'BlueShift-iOS-Extension-SDK'
end
